### ISSUE TITLE
Spawner should support an array for what is to spawn

### ISSUE THREAD

**Issue by tom95** [hpi-swa-lab/godot-pronto#46]
Open question: how to select which child to spawn?

Suggestion: new method, otherwise always pick first

**Comment by Nsgr** [comment]
The supposed array is now just based off of all children of the Spawner, and an optional "index" argument for spawning methods was added. Since just spawning the first node is probably a behavior that would be more suitable for separating spawners in the first place, by default, a spawner now spawns all children.
